import { CurrencyPipe } from '@angular/common';
import { Component, OnDestroy, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';

type CustomerTab='home'|'explore'|'orders'|'profile';
interface PublicDish{id:number;nombre:string;descripcion:string;precio:number;disponible:boolean;categoria?:{nombre:string}}

@Component({selector:'app-cliente',standalone:true,imports:[FormsModule,CurrencyPipe],template:`
@if(splash()){<div class="customer-splash"><img src="/digital-waiter-splash.png" alt="Digital Waiter"></div>}
<main class="customer-app">
 <header class="customer-header"><img src="/digital-waiter-logo-v1.png" alt="Digital Waiter"><span>Ordena fácil · disfruta más</span></header>
 <div class="customer-content">
 @if(tab()==='home'){
  <section class="customer-greeting"><small>HOLA{{customerName?', '+customerName.toUpperCase():''}} 👋</small><h1>¿Qué deseas comer hoy?</h1><label class="customer-search">⌕ <input [(ngModel)]="search" (focus)="tab.set('explore')" placeholder="Buscar restaurante o plato"></label></section>
  <div class="quick-actions"><button (click)="qrOpen.set(true)"><b>▣</b><span>Escanear QR</span><small>Pide desde tu mesa</small></button><button (click)="startPickup()"><b>◷</b><span>Pedido anticipado</span><small>Retira sin esperar</small></button></div>
  <section class="customer-section"><div class="section-heading"><div><small>CERCA DE TI</small><h2>Restaurantes</h2></div><button (click)="tab.set('explore')">Ver carta</button></div>
   <button class="restaurant-card" (click)="tab.set('explore')"><div class="restaurant-visual"><span>🍲</span><i>ABIERTO</i></div><div><h3>{{restaurant()?.nombre||'Sazón de Casa'}}</h3><p>{{restaurant()?.descripcion}}</p><small>★ 4.8 · {{restaurant()?.tiempo}} · {{restaurant()?.direccion}}</small></div></button>
  </section>
  <section class="customer-section"><div class="section-heading"><div><small>ENCUENTRA RÁPIDO</small><h2>Categorías</h2></div></div><div class="category-scroll">@for(c of categories();track c){<button (click)="chooseCategory(c)"><span>{{categoryIcon(c)}}</span>{{c}}</button>}</div></section>
  @if(currentOrder()){<button class="current-order" (click)="tab.set('orders')"><span>Pedido {{currentOrder().codigoRetiro}}</span><b>{{statusLabel(currentOrder().estado)}} →</b></button>}
 }
 @if(tab()==='explore'){
  <section class="catalog-head"><button (click)="tab.set('home')">←</button><div><small>{{restaurant()?.nombre}}</small><h1>Elige lo que te gusta</h1></div></section>
  <label class="customer-search">⌕ <input [(ngModel)]="search" placeholder="Buscar en la carta"></label>
  <div class="catalog-filters"><button [class.active]="category()===''" (click)="category.set('')">Todo</button>@for(c of categories();track c){<button [class.active]="category()===c" (click)="category.set(c)">{{c}}</button>}</div>
  <div class="customer-menu">@for(dish of filteredMenu();track dish.id){<article><div class="dish-customer-art">{{categoryIcon(dish.categoria?.nombre||'')}}</div><div><small>{{dish.categoria?.nombre}}</small><h3>{{dish.nombre}}</h3><p>{{dish.descripcion||'Preparado al momento con ingredientes seleccionados.'}}</p><footer><b>{{dish.precio|currency:'USD'}}</b><button (click)="add(dish.id)">{{quantity(dish.id)?quantity(dish.id)+' en carrito':'+'}}</button></footer></div></article>}@empty{<p class="empty">No encontramos platos con esa búsqueda.</p>}</div>
 }
 @if(tab()==='orders'){
  <section class="catalog-head"><button (click)="tab.set('home')">←</button><div><small>SEGUIMIENTO</small><h1>Tu pedido</h1></div></section>
  @if(currentOrder();as order){<article class="tracking-card"><div class="tracking-code"><small>CÓDIGO</small><b>{{order.codigoRetiro}}</b></div><h2>{{statusLabel(order.estado)}}</h2><p>{{order.modalidad==='pickup'?'Te avisaremos cuando puedas retirar tu pedido.':'Tu pedido llegará a la mesa '+order.mesa?.numero+'.'}}</p><div class="tracking-steps">@for(step of steps;track step.value;let i=$index){<div [class.done]="statusIndex(order.estado)>=i"><i>{{statusIndex(order.estado)>i?'✓':i+1}}</i><span>{{step.label}}</span></div>}</div><div class="tracking-summary">@for(line of order.detalles;track line.id){<span>{{line.cantidad}} × {{line.producto.nombre}}</span>}</div><button class="small-button wide" (click)="refreshOrder()">↻ Actualizar estado</button></article>}@else{<section class="customer-empty"><span>🧾</span><h2>Aún no tienes pedidos</h2><p>Explora la carta y realiza tu primera orden.</p><button class="primary" (click)="tab.set('explore')">Ver carta</button></section>}
 }
 @if(tab()==='profile'){
  <section class="catalog-head"><button (click)="tab.set('home')">←</button><div><small>CUENTA</small><h1>Tu perfil</h1></div></section><section class="profile-card"><div class="profile-avatar">{{customerName?customerName[0].toUpperCase():'C'}}</div><label>Nombre<input [(ngModel)]="customerName" placeholder="Tu nombre"></label><label>Teléfono<input [(ngModel)]="phone" inputmode="tel" placeholder="09 9999 9999"></label><button class="primary wide" (click)="saveProfile()">Guardar datos</button></section>
 }
 </div>
 @if(cartCount()){<button class="cart-bar" (click)="checkoutOpen.set(true)"><span>{{cartCount()}} producto(s)</span><b>Ver pedido · {{cartTotal()|currency:'USD'}}</b></button>}
 <nav class="customer-nav"><button [class.active]="tab()==='home'" (click)="tab.set('home')"><span>⌂</span>Inicio</button><button [class.active]="tab()==='explore'" (click)="tab.set('explore')"><span>⌕</span>Explorar</button><button [class.active]="tab()==='orders'" (click)="tab.set('orders')"><span>▤</span>Pedidos</button><button [class.active]="tab()==='profile'" (click)="tab.set('profile')"><span>♙</span>Perfil</button></nav>
</main>
@if(checkoutOpen()){<div class="customer-modal" (click)="checkoutOpen.set(false)"><section (click)="$event.stopPropagation()"><button class="dialog-close" (click)="checkoutOpen.set(false)">×</button><small>CONFIRMAR PEDIDO</small><h2>¿Cómo lo recibirás?</h2><div class="fulfillment"><button [class.active]="modality==='dinein'" (click)="modality='dinein'">🍽 Comer aquí</button><button [class.active]="modality==='pickup'" (click)="modality='pickup'">🥡 Retirar</button></div>@for(dish of cartItems();track dish.id){<div class="checkout-line"><div><b>{{dish.nombre}}</b><small>{{dish.precio|currency:'USD'}}</small></div><div><button (click)="remove(dish.id)">−</button><b>{{quantity(dish.id)}}</b><button (click)="add(dish.id)">+</button></div></div>}<label>Nombre<input [(ngModel)]="customerName" placeholder="Nombre del cliente"></label><label>Teléfono<input [(ngModel)]="phone" inputmode="tel" placeholder="0999999999"></label>@if(modality==='dinein'){<label>Número de mesa<input [(ngModel)]="tableNumber" type="number" min="1"></label>}@else{<label>Hora aproximada de retiro<input [(ngModel)]="pickupTime" type="time"></label>}<label>Indicaciones<textarea [(ngModel)]="notes" placeholder="Sin cebolla, alergias u otra indicación"></textarea></label>@if(error()){<p class="form-error">{{error()}}</p>}<button class="primary wide" [disabled]="sending()" (click)="sendOrder()">{{sending()?'Enviando…':'Confirmar · '+(cartTotal()|currency:'USD')}}</button></section></div>}
@if(qrOpen()){<div class="customer-modal" (click)="qrOpen.set(false)"><section (click)="$event.stopPropagation()"><button class="dialog-close" (click)="qrOpen.set(false)">×</button><small>ACCESO RÁPIDO</small><h2>Escanea el QR de tu mesa</h2><label class="qr-capture">📷 Abrir cámara<input type="file" accept="image/*" capture="environment" (change)="readQr($event)"></label><p>O escribe el código impreso, por ejemplo <b>MESA-4</b>.</p><label>Código QR<input [(ngModel)]="qrCode" placeholder="MESA-4"></label>@if(qrMessage()){<p class="form-error">{{qrMessage()}}</p>}<button class="primary wide" (click)="applyQr(qrCode)">Abrir carta</button></section></div>}
`})
export class ClienteComponent implements OnDestroy{
 private api=inject(ApiService);splash=signal(true);tab=signal<CustomerTab>('home');restaurant=signal<any>(null);menu=signal<PublicDish[]>([]);search='';category=signal('');cart=signal<Record<number,number>>({});checkoutOpen=signal(false);qrOpen=signal(false);currentOrder=signal<any>(null);error=signal('');qrMessage=signal('');sending=signal(false);modality:'dinein'|'pickup'='pickup';customerName=localStorage.getItem('dwCustomerName')||'';phone=localStorage.getItem('dwCustomerPhone')||'';tableNumber=1;pickupTime='';notes='';qrCode='';
 steps=[{value:'new',label:'Confirmado'},{value:'preparing',label:'Preparando'},{value:'ready',label:'Listo'},{value:'payment',label:'Por retirar'},{value:'paid',label:'Completado'}];private timer=window.setInterval(()=>this.refreshOrder(),5000);
 categories=computed(()=>[...new Set(this.menu().map(m=>m.categoria?.nombre||'Otros'))]);filteredMenu=computed(()=>{const q=this.normalized(this.search),c=this.category();return this.menu().filter(m=>m.disponible&&(!c||m.categoria?.nombre===c)&&(!q||this.normalized(m.nombre+' '+m.descripcion).includes(q)))});cartItems=computed(()=>this.menu().filter(m=>this.quantity(m.id)>0));cartCount=computed(()=>Object.values(this.cart()).reduce((a,b)=>a+b,0));cartTotal=computed(()=>this.cartItems().reduce((sum,m)=>sum+Number(m.precio)*this.quantity(m.id),0));
 constructor(){window.setTimeout(()=>this.splash.set(false),1400);this.load();const code=localStorage.getItem('dwCustomerOrder');if(code)this.loadOrder(code)}ngOnDestroy(){window.clearInterval(this.timer)}
 async load(){try{const data=await this.api.restaurantePublico();this.restaurant.set(data);this.menu.set(data.menu)}catch{this.error.set('No fue posible cargar la carta.') }}
 normalized(v:string){return(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
 categoryIcon(c:string){const v=this.normalized(c);return v.includes('bebida')?'🥤':v.includes('postre')?'🍮':v.includes('entrada')?'🥣':v.includes('rapida')?'🍔':'🍲'}
 chooseCategory(c:string){this.category.set(c);this.tab.set('explore')}quantity(id:number){return this.cart()[id]||0}add(id:number){this.cart.update(x=>({...x,[id]:(x[id]||0)+1}))}remove(id:number){this.cart.update(x=>{const next={...x};next[id]=(next[id]||0)-1;if(next[id]<=0)delete next[id];return next})}
 startPickup(){this.modality='pickup';this.tab.set('explore')}
 async sendOrder(){this.error.set('');if(this.customerName.trim().length<2){this.error.set('Ingresa tu nombre.');return}if(this.phone.replace(/\D/g,'').length<7){this.error.set('Ingresa un teléfono válido.');return}if(this.modality==='dinein'&&this.tableNumber<1){this.error.set('Indica tu mesa.');return}this.sending.set(true);try{const order=await this.api.crearPedidoPublico({cliente:this.customerName,telefono:this.phone,modalidad:this.modality,mesaNumero:this.modality==='dinein'?Number(this.tableNumber):undefined,horaRetiro:this.modality==='pickup'?this.pickupTime:undefined,notas:this.notes,detalles:Object.entries(this.cart()).map(([id,cantidad])=>({productoId:Number(id),cantidad}))});this.currentOrder.set(order);localStorage.setItem('dwCustomerOrder',order.codigoRetiro);this.saveProfile();this.cart.set({});this.checkoutOpen.set(false);this.tab.set('orders')}catch(e:any){this.error.set(Array.isArray(e?.error?.message)?e.error.message.join('. '):e?.error?.message||'No fue posible registrar el pedido.')}finally{this.sending.set(false)}}
  async loadOrder(code:string){try{this.currentOrder.set(await this.api.seguirPedidoPublico(code));this.error.set('')}catch{this.error.set('No pudimos actualizar el pedido. Conservamos tu código para volver a intentarlo.')}}async refreshOrder(){const code=localStorage.getItem('dwCustomerOrder');if(code)await this.loadOrder(code)}statusIndex(s:string){return Math.max(0,this.steps.findIndex(x=>x.value===s))}statusLabel(s:string){return({new:'Pedido confirmado',preparing:'Preparando tu pedido',ready:'¡Tu pedido está listo!',payment:'Listo para cobrar',paid:'Pedido completado'} as Record<string,string>)[s]||s}
 saveProfile(){localStorage.setItem('dwCustomerName',this.customerName);localStorage.setItem('dwCustomerPhone',this.phone)}
 applyQr(value:string){const table=Number(value.match(/(\d+)/)?.[1]);if(!table){this.qrMessage.set('No reconocimos el número de mesa.');return}this.tableNumber=table;this.modality='dinein';this.qrOpen.set(false);this.tab.set('explore')}
 async readQr(event:Event){const input=event.target as HTMLInputElement,file=input.files?.[0],Detector=(window as any).BarcodeDetector;if(!file||!Detector){this.qrMessage.set('Tu dispositivo no admite lectura automática. Escribe el código de la mesa.');return}try{const bitmap=await createImageBitmap(file),codes=await new Detector({formats:['qr_code']}).detect(bitmap);if(!codes.length)throw new Error();this.qrCode=codes[0].rawValue;this.applyQr(this.qrCode)}catch{this.qrMessage.set('No pudimos leer ese QR. Intenta nuevamente o escribe el código.')}}
}
