import { Component, OnDestroy, computed } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { AuthService } from '../../core/services/auth.service';
import { StoreService } from '../../core/services/store.service';
import { NotificationService } from '../../core/services/notification.service';
import { AsistenteVozComponent } from '../../features/asistente-voz/asistente-voz.component';

@Component({selector:'app-shell',standalone:true,imports:[RouterOutlet,RouterLink,RouterLinkActive,AsistenteVozComponent],template:`
<div class="app-shell"><aside><div class="brand"><span>⌁</span><b>DIGITAL <i>WAITER</i></b></div><div class="profile"><div>{{initials()}}</div><span><b>{{store.session()?.name}}</b><small>{{store.session()?.role}}</small></span></div><nav>@for(n of visibleNav();track n.path){<a [routerLink]="n.path" routerLinkActive="active"><span>{{n.icon}}</span>{{n.label}} @if(n.count){<i>{{n.count()}}</i>}</a>}</nav><button class="logout" (click)="auth.logout()">↪ Cerrar sesión</button><button class="mobile-logout" (click)="auth.logout()" aria-label="Cerrar sesión"><span>↪</span>Salir</button></aside><main><header><div><h1>Digital Waiter</h1><p>Gestión inteligente para restaurantes</p></div><div class="header-actions"><button class="notification-toggle" (click)="notifications.enable()">{{notifications.enabled()?'🔔 Avisos activos':'🔕 Activar avisos'}}</button><time>{{today}}</time></div></header>@if(store.error()){<div class="system-alert"><span>⚠ {{store.error()}}</span><button (click)="store.loadAll(true)">Reintentar</button></div>}@if(store.loading()){<div class="loading-line"></div>}<section class="page"><router-outlet/></section></main></div><app-asistente-voz/>@if(!notifications.enabled()){<button class="mobile-alert-toggle" (click)="notifications.enable()">🔔 Activar avisos</button>}<div class="toast-stack">@for(note of notifications.messages();track note.id){<button class="app-toast" [class]="'app-toast '+note.kind" (click)="notifications.remove(note.id)"><b>{{note.title}}</b><span>{{note.body}}</span></button>}</div>`})
export class ShellComponent implements OnDestroy {
  today=new Date().toLocaleDateString('es-EC',{weekday:'long',day:'numeric',month:'long'});
  nav=[{path:'/inicio',label:'Inicio',icon:'▦',roles:['Administrador','Mesero','Cajero']},{path:'/pedidos',label:'Pedidos',icon:'▤',roles:['Administrador','Mesero','Cajero'],count:()=>this.store.orders().filter(o=>o.status!=='paid').length},{path:'/mesas',label:'Mesas',icon:'▱',roles:['Administrador','Mesero','Cajero'],count:()=>this.store.tables().length},{path:'/cocina',label:'Cocina',icon:'◴',roles:['Administrador','Cocina'],count:()=>this.store.orders().filter(o=>['new','preparing','ready'].includes(o.status)).length},{path:'/menu',label:'Menú',icon:'☰',roles:['Administrador','Mesero','Cocina']},{path:'/inventario',label:'Inventario',icon:'◇',roles:['Administrador'],count:()=>this.store.inventory().filter(i=>i.stock<=i.min).length},{path:'/asistente',label:'Asistente IA',icon:'✦',roles:['Administrador']},{path:'/usuarios',label:'Usuarios',icon:'♙',roles:['Administrador']},{path:'/reportes',label:'Reportes',icon:'⌁',roles:['Administrador','Cajero']}];
  visibleNav=computed(()=>this.nav.filter(n=>n.roles.includes(this.store.session()?.role||'')));
  initials=computed(()=>this.store.session()?.name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase());
  private timer=window.setInterval(()=>this.store.loadAll(),5000);
  constructor(public store:StoreService,public auth:AuthService,public notifications:NotificationService){this.store.loadAll(true)}
  ngOnDestroy(){window.clearInterval(this.timer)}
}
